//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/utils/res/XResources_it.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlUtilsResXResources_it")
#ifdef RESTRICT_OrgApacheXmlUtilsResXResources_it
#define INCLUDE_ALL_OrgApacheXmlUtilsResXResources_it 0
#else
#define INCLUDE_ALL_OrgApacheXmlUtilsResXResources_it 1
#endif
#undef RESTRICT_OrgApacheXmlUtilsResXResources_it

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgApacheXmlUtilsResXResources_it_) && (INCLUDE_ALL_OrgApacheXmlUtilsResXResources_it || defined(INCLUDE_OrgApacheXmlUtilsResXResources_it))
#define OrgApacheXmlUtilsResXResources_it_

#define RESTRICT_OrgApacheXmlUtilsResXResourceBundle 1
#define INCLUDE_OrgApacheXmlUtilsResXResourceBundle 1
#include "org/apache/xml/utils/res/XResourceBundle.h"

@class IOSObjectArray;

/*!
 @brief The Italian resource bundle.
 */
@interface OrgApacheXmlUtilsResXResources_it : OrgApacheXmlUtilsResXResourceBundle

#pragma mark Public

- (instancetype __nonnull)init;

/*!
 @brief Get the association list.
 @return The association list.
 */
- (IOSObjectArray *)getContents;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlUtilsResXResources_it)

FOUNDATION_EXPORT void OrgApacheXmlUtilsResXResources_it_init(OrgApacheXmlUtilsResXResources_it *self);

FOUNDATION_EXPORT OrgApacheXmlUtilsResXResources_it *new_OrgApacheXmlUtilsResXResources_it_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlUtilsResXResources_it *create_OrgApacheXmlUtilsResXResources_it_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlUtilsResXResources_it)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlUtilsResXResources_it")
