//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/utils/res/XResources_fr.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlUtilsResXResources_fr")
#ifdef RESTRICT_OrgApacheXmlUtilsResXResources_fr
#define INCLUDE_ALL_OrgApacheXmlUtilsResXResources_fr 0
#else
#define INCLUDE_ALL_OrgApacheXmlUtilsResXResources_fr 1
#endif
#undef RESTRICT_OrgApacheXmlUtilsResXResources_fr

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgApacheXmlUtilsResXResources_fr_) && (INCLUDE_ALL_OrgApacheXmlUtilsResXResources_fr || defined(INCLUDE_OrgApacheXmlUtilsResXResources_fr))
#define OrgApacheXmlUtilsResXResources_fr_

#define RESTRICT_OrgApacheXmlUtilsResXResourceBundle 1
#define INCLUDE_OrgApacheXmlUtilsResXResourceBundle 1
#include "org/apache/xml/utils/res/XResourceBundle.h"

@class IOSObjectArray;

/*!
 @brief The French resource bundle.
 */
@interface OrgApacheXmlUtilsResXResources_fr : OrgApacheXmlUtilsResXResourceBundle

#pragma mark Public

- (instancetype __nonnull)init;

/*!
 @brief Get the association list.
 @return The association list.
 */
- (IOSObjectArray *)getContents;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlUtilsResXResources_fr)

FOUNDATION_EXPORT void OrgApacheXmlUtilsResXResources_fr_init(OrgApacheXmlUtilsResXResources_fr *self);

FOUNDATION_EXPORT OrgApacheXmlUtilsResXResources_fr *new_OrgApacheXmlUtilsResXResources_fr_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlUtilsResXResources_fr *create_OrgApacheXmlUtilsResXResources_fr_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlUtilsResXResources_fr)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlUtilsResXResources_fr")
