//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/hamcrest/Condition.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgHamcrestCondition")
#ifdef RESTRICT_OrgHamcrestCondition
#define INCLUDE_ALL_OrgHamcrestCondition 0
#else
#define INCLUDE_ALL_OrgHamcrestCondition 1
#endif
#undef RESTRICT_OrgHamcrestCondition
#ifdef INCLUDE_OrgHamcrestCondition_NotMatched
#define INCLUDE_OrgHamcrestCondition 1
#endif

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgHamcrestCondition_) && (INCLUDE_ALL_OrgHamcrestCondition || defined(INCLUDE_OrgHamcrestCondition))
#define OrgHamcrestCondition_

@class OrgHamcrestCondition_NotMatched;
@protocol OrgHamcrestCondition_Step;
@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

/*!
 @brief A Condition implements part of a multi-step match.We sometimes need to write matchers
  that have a sequence of steps, where each step depends on the result of the previous
  step and we can stop processing as soon as a step fails.
 These classes provide
  infrastructure for writing such a sequence.
  Based on https://github.com/npryce/maybe-java
 @author Steve Freeman 2012 http://www.hamcrest.com
 */
@interface OrgHamcrestCondition : NSObject
@property (readonly, class, strong) OrgHamcrestCondition_NotMatched *NOT_MATCHED NS_SWIFT_NAME(NOT_MATCHED);

+ (OrgHamcrestCondition_NotMatched *)NOT_MATCHED;

#pragma mark Public

- (OrgHamcrestCondition *)and__WithOrgHamcrestCondition_Step:(id<OrgHamcrestCondition_Step>)mapping;

+ (OrgHamcrestCondition *)matchedWithId:(id)theValue
             withOrgHamcrestDescription:(id<OrgHamcrestDescription>)mismatch;

- (jboolean)matchingWithOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)match;

- (jboolean)matchingWithOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)match
                              withNSString:(NSString *)message;

+ (OrgHamcrestCondition *)notMatched;

- (OrgHamcrestCondition *)thenWithOrgHamcrestCondition_Step:(id<OrgHamcrestCondition_Step>)mapping;

@end

J2OBJC_STATIC_INIT(OrgHamcrestCondition)

inline OrgHamcrestCondition_NotMatched *OrgHamcrestCondition_get_NOT_MATCHED(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgHamcrestCondition_NotMatched *OrgHamcrestCondition_NOT_MATCHED;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgHamcrestCondition, NOT_MATCHED, OrgHamcrestCondition_NotMatched *)

FOUNDATION_EXPORT OrgHamcrestCondition *OrgHamcrestCondition_notMatched(void);

FOUNDATION_EXPORT OrgHamcrestCondition *OrgHamcrestCondition_matchedWithId_withOrgHamcrestDescription_(id theValue, id<OrgHamcrestDescription> mismatch);

J2OBJC_TYPE_LITERAL_HEADER(OrgHamcrestCondition)

#endif

#if !defined (OrgHamcrestCondition_Step_) && (INCLUDE_ALL_OrgHamcrestCondition || defined(INCLUDE_OrgHamcrestCondition_Step))
#define OrgHamcrestCondition_Step_

@class OrgHamcrestCondition;
@protocol OrgHamcrestDescription;

@protocol OrgHamcrestCondition_Step < JavaObject >

- (OrgHamcrestCondition *)applyWithId:(id)value
           withOrgHamcrestDescription:(id<OrgHamcrestDescription>)mismatch;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgHamcrestCondition_Step)

J2OBJC_TYPE_LITERAL_HEADER(OrgHamcrestCondition_Step)

#endif

#if !defined (OrgHamcrestCondition_NotMatched_) && (INCLUDE_ALL_OrgHamcrestCondition || defined(INCLUDE_OrgHamcrestCondition_NotMatched))
#define OrgHamcrestCondition_NotMatched_

@class OrgHamcrestCondition;
@protocol OrgHamcrestCondition_Step;
@protocol OrgHamcrestMatcher;

@interface OrgHamcrestCondition_NotMatched : OrgHamcrestCondition

#pragma mark Public

- (OrgHamcrestCondition *)and__WithOrgHamcrestCondition_Step:(id<OrgHamcrestCondition_Step>)mapping;

- (jboolean)matchingWithOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)match
                              withNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgHamcrestCondition_NotMatched)

J2OBJC_TYPE_LITERAL_HEADER(OrgHamcrestCondition_NotMatched)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgHamcrestCondition")
