//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/ojluni/src/main/java/java/lang/UnsatisfiedLinkError.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaLangUnsatisfiedLinkError")
#ifdef RESTRICT_JavaLangUnsatisfiedLinkError
#define INCLUDE_ALL_JavaLangUnsatisfiedLinkError 0
#else
#define INCLUDE_ALL_JavaLangUnsatisfiedLinkError 1
#endif
#undef RESTRICT_JavaLangUnsatisfiedLinkError

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (JavaLangUnsatisfiedLinkError_) && (INCLUDE_ALL_JavaLangUnsatisfiedLinkError || defined(INCLUDE_JavaLangUnsatisfiedLinkError))
#define JavaLangUnsatisfiedLinkError_

#define RESTRICT_JavaLangLinkageError 1
#define INCLUDE_JavaLangLinkageError 1
#include "java/lang/LinkageError.h"

@class JavaLangThrowable;

/*!
 @brief Thrown if the Java Virtual Machine cannot find an appropriate
  native-language definition of a method declared <code>native</code>.
 @author unascribed
 - seealso: java.lang.Runtime
 @since JDK1.0
 */
@interface JavaLangUnsatisfiedLinkError : JavaLangLinkageError

#pragma mark Public

/*!
 @brief Constructs an <code>UnsatisfiedLinkError</code> with no detail message.
 */
- (instancetype __nonnull)init;

/*!
 @brief Constructs an <code>UnsatisfiedLinkError</code> with the
  specified detail message.
 @param s the detail message.
 */
- (instancetype __nonnull)initWithNSString:(NSString *)s;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangUnsatisfiedLinkError)

FOUNDATION_EXPORT void JavaLangUnsatisfiedLinkError_init(JavaLangUnsatisfiedLinkError *self);

FOUNDATION_EXPORT JavaLangUnsatisfiedLinkError *new_JavaLangUnsatisfiedLinkError_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaLangUnsatisfiedLinkError *create_JavaLangUnsatisfiedLinkError_init(void);

FOUNDATION_EXPORT void JavaLangUnsatisfiedLinkError_initWithNSString_(JavaLangUnsatisfiedLinkError *self, NSString *s);

FOUNDATION_EXPORT JavaLangUnsatisfiedLinkError *new_JavaLangUnsatisfiedLinkError_initWithNSString_(NSString *s) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaLangUnsatisfiedLinkError *create_JavaLangUnsatisfiedLinkError_initWithNSString_(NSString *s);

J2OBJC_TYPE_LITERAL_HEADER(JavaLangUnsatisfiedLinkError)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_JavaLangUnsatisfiedLinkError")
