//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/testing/mockito/build_result/java/org/mockito/internal/listeners/StubbingLookupNotifier.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupNotifier")
#ifdef RESTRICT_OrgMockitoInternalListenersStubbingLookupNotifier
#define INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupNotifier 0
#else
#define INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupNotifier 1
#endif
#undef RESTRICT_OrgMockitoInternalListenersStubbingLookupNotifier

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalListenersStubbingLookupNotifier_) && (INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupNotifier || defined(INCLUDE_OrgMockitoInternalListenersStubbingLookupNotifier))
#define OrgMockitoInternalListenersStubbingLookupNotifier_

@class OrgMockitoInternalCreationSettingsCreationSettings;
@protocol JavaUtilCollection;
@protocol OrgMockitoInvocationInvocation;
@protocol OrgMockitoStubbingStubbing;

@interface OrgMockitoInternalListenersStubbingLookupNotifier : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

+ (void)notifyStubbedAnswerLookupWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)invocation
                                     withOrgMockitoStubbingStubbing:(id<OrgMockitoStubbingStubbing>)stubbingFound
                                             withJavaUtilCollection:(id<JavaUtilCollection>)allStubbings
             withOrgMockitoInternalCreationSettingsCreationSettings:(OrgMockitoInternalCreationSettingsCreationSettings *)creationSettings;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalListenersStubbingLookupNotifier)

FOUNDATION_EXPORT void OrgMockitoInternalListenersStubbingLookupNotifier_init(OrgMockitoInternalListenersStubbingLookupNotifier *self);

FOUNDATION_EXPORT OrgMockitoInternalListenersStubbingLookupNotifier *new_OrgMockitoInternalListenersStubbingLookupNotifier_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalListenersStubbingLookupNotifier *create_OrgMockitoInternalListenersStubbingLookupNotifier_init(void);

FOUNDATION_EXPORT void OrgMockitoInternalListenersStubbingLookupNotifier_notifyStubbedAnswerLookupWithOrgMockitoInvocationInvocation_withOrgMockitoStubbingStubbing_withJavaUtilCollection_withOrgMockitoInternalCreationSettingsCreationSettings_(id<OrgMockitoInvocationInvocation> invocation, id<OrgMockitoStubbingStubbing> stubbingFound, id<JavaUtilCollection> allStubbings, OrgMockitoInternalCreationSettingsCreationSettings *creationSettings);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalListenersStubbingLookupNotifier)

#endif

#if !defined (OrgMockitoInternalListenersStubbingLookupNotifier_Event_) && (INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupNotifier || defined(INCLUDE_OrgMockitoInternalListenersStubbingLookupNotifier_Event))
#define OrgMockitoInternalListenersStubbingLookupNotifier_Event_

#define RESTRICT_OrgMockitoInternalListenersStubbingLookupEvent 1
#define INCLUDE_OrgMockitoInternalListenersStubbingLookupEvent 1
#include "org/mockito/internal/listeners/StubbingLookupEvent.h"

@protocol JavaUtilCollection;
@protocol OrgMockitoInvocationInvocation;
@protocol OrgMockitoMockMockCreationSettings;
@protocol OrgMockitoStubbingStubbing;

@interface OrgMockitoInternalListenersStubbingLookupNotifier_Event : NSObject < OrgMockitoInternalListenersStubbingLookupEvent >

#pragma mark Public

- (instancetype __nonnull)initWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)invocation
                                  withOrgMockitoStubbingStubbing:(id<OrgMockitoStubbingStubbing>)stubbing
                                          withJavaUtilCollection:(id<JavaUtilCollection>)allStubbings
                          withOrgMockitoMockMockCreationSettings:(id<OrgMockitoMockMockCreationSettings>)mockSettings;

- (id<JavaUtilCollection>)getAllStubbings;

- (id<OrgMockitoInvocationInvocation>)getInvocation;

- (id<OrgMockitoMockMockCreationSettings>)getMockSettings;

- (id<OrgMockitoStubbingStubbing>)getStubbingFound;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalListenersStubbingLookupNotifier_Event)

FOUNDATION_EXPORT void OrgMockitoInternalListenersStubbingLookupNotifier_Event_initWithOrgMockitoInvocationInvocation_withOrgMockitoStubbingStubbing_withJavaUtilCollection_withOrgMockitoMockMockCreationSettings_(OrgMockitoInternalListenersStubbingLookupNotifier_Event *self, id<OrgMockitoInvocationInvocation> invocation, id<OrgMockitoStubbingStubbing> stubbing, id<JavaUtilCollection> allStubbings, id<OrgMockitoMockMockCreationSettings> mockSettings);

FOUNDATION_EXPORT OrgMockitoInternalListenersStubbingLookupNotifier_Event *new_OrgMockitoInternalListenersStubbingLookupNotifier_Event_initWithOrgMockitoInvocationInvocation_withOrgMockitoStubbingStubbing_withJavaUtilCollection_withOrgMockitoMockMockCreationSettings_(id<OrgMockitoInvocationInvocation> invocation, id<OrgMockitoStubbingStubbing> stubbing, id<JavaUtilCollection> allStubbings, id<OrgMockitoMockMockCreationSettings> mockSettings) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalListenersStubbingLookupNotifier_Event *create_OrgMockitoInternalListenersStubbingLookupNotifier_Event_initWithOrgMockitoInvocationInvocation_withOrgMockitoStubbingStubbing_withJavaUtilCollection_withOrgMockitoMockMockCreationSettings_(id<OrgMockitoInvocationInvocation> invocation, id<OrgMockitoStubbingStubbing> stubbing, id<JavaUtilCollection> allStubbings, id<OrgMockitoMockMockCreationSettings> mockSettings);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalListenersStubbingLookupNotifier_Event)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupNotifier")
