import platform.Foundation.*

val doesNotWork = "PT09IEVSRUlHTklTTElTVEUgPT09PT09ChtLbgpCRUdJTk4gICAgICAgMjguMDYgMTM6MjUKRVJFSUdOSVNTRSAgICAgICAgICAgIDYyCjUwIDUgICAgICAgICAgMjguMDYgMTMyNQozNDAyICAgICAgICAgIDI4LjA2IDEzMjUKMzQxMiAgICAgICAgICAyOC4wNiAxMzI1CjYzIDMgICAgICAgICAgMjguMDYgMTMyNQo2MyAwICAgICAgICAgIDI4LjA2IDEzMjUKRUUwNiAgICAgICAgICAyOC4wNiAxMzI1CkVFMDYgICAgICAgICAgMjguMDYgMTMyMgpFRTA3ICAgICAgICAgIDI4LjA2IDEzMjIKNjMgMyAgICAgICAgICAyOC4wNiAxMzIyCkVFMDYgICAgICAgICAgMjguMDYgMTMyMgpFRTA3ICAgICAgICAgIDI4LjA2IDEzMjIKNjMgMyAgICAgICAgICAyOC4wNiAxMzIyCjYzIDMgICAgICAgICAgMjguMDYgMTMyMgo2MyAzICAgICAgICAgIDI4LjA2IDEzMjMKNjMgMyAgICAgICAgICAyOC4wNiAxNTAwCjUwIDQgICAgICAgICAgMjguMDYgMTUwMAo1MCA1ICAgICAgICAgIDMwLjA2IDEyMjYKMzQwMiAgICAgICAgICAzMC4wNiAxMjI2CjM0MTIgICAgICAgICAgMzAuMDYgMTIyNgo1MCA0ICAgICAgICAgIDMwLjA2IDEyMjcKNTAgNSAgICAgICAgICAzMC4wNiAxMjI4CjM0MDIgICAgICAgICAgMzAuMDYgMTIyOAo="
val works = "PT09IEVSRUlHTklTTElTVEUgPT09PT09ChtLbgpCRUdJTk4gICAgICAgMjguMDYgMTM6MjUKRVJFSUdOSVNTRSAgICAgICAgICAgIDYyCjUwIDUgICAgICAgICAgMjguMDYgMTMyNQozNDAyICAgICAgICAgIDI4LjA2IDEzMjUKMzQxMiAgICAgICAgICAyOC4wNiAxMzI1CjYzIDMgICAgICAgICAgMjguMDYgMTMyNQo2MyAwICAgICAgICAgIDI4LjA2IDEzMjUKRUUwNiAgICAgICAgICAyOC4wNiAxMzI1CkVFMDYgICAgICAgICAgMjguMDYgMTMyMgpFRTA3ICAgICAgICAgIDI4LjA2IDEzMjIKNjMgMyAgICAgICAgICAyOC4wNiAxMzIyCkVFMDYgICAgICAgICAgMjguMDYgMTMyMgpFRTA3ICAgICAgICAgIDI4LjA2IDEzMjIKNjMgMyAgICAgICAgICAyOC4wNiAxMzIyCjYzIDMgICAgICAgICAgMjguMDYgMTMyMgo2MyAzICAgICAgICAgIDI4LjA2IDEzMjMKNjMgMyAgICAgICAgICAyOC4wNiAxNTAwCjUwIDQgICAgICAgICAgMjguMDYgMTUwMAo1MCA1ICAgICAgICAgIDMwLjA2IDEyMjYKMzQwMiAgICAgICAgICAzMC4wNiAxMjI2CjM0MTIgICAgICAgICAgMzAuMDYgMTIyNgo1MCA0ICAgICAgICAgIDMwLjA2IDEyMjcKNTAgNSAgICAgICAgICAzMC4wNiAxMjI4Cg=="
fun base64Decoded(string: String):NSString {
    val decodedData =  NSData.create(base64EncodedString = string, options = NSDataBase64DecodingOptions.MAX_VALUE)
    val decodedString = NSString.create(data= decodedData!!, encoding= NSASCIIStringEncoding)
    return decodedString!!
}

val REGEX = Regex("(\\x1b\\w[\\s\\S]{1,2})([\\s\\S]+?(?=\\x1b\\w[\\s\\S]{1,2}|\$))")

fun regexTest(content: String): List<String> {
    return REGEX.findAll(content).map {
        it.groupValues[1]
    }.toList()
}

fun f35508(){
    println(regexTest(base64Decoded(works) as String))
    println("First string succeeded")
    println(regexTest(base64Decoded(doesNotWork) as String))
    println("Second string succeeded")
}

fun main() {
 f35508()
 }