//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/ojluni/src/main/java/java/nio/channels/ClosedByInterruptException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaNioChannelsClosedByInterruptException")
#ifdef RESTRICT_JavaNioChannelsClosedByInterruptException
#define INCLUDE_ALL_JavaNioChannelsClosedByInterruptException 0
#else
#define INCLUDE_ALL_JavaNioChannelsClosedByInterruptException 1
#endif
#undef RESTRICT_JavaNioChannelsClosedByInterruptException

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (JavaNioChannelsClosedByInterruptException_) && (INCLUDE_ALL_JavaNioChannelsClosedByInterruptException || defined(INCLUDE_JavaNioChannelsClosedByInterruptException))
#define JavaNioChannelsClosedByInterruptException_

#define RESTRICT_JavaNioChannelsAsynchronousCloseException 1
#define INCLUDE_JavaNioChannelsAsynchronousCloseException 1
#include "java/nio/channels/AsynchronousCloseException.h"

/*!
 @brief Checked exception received by a thread when another thread interrupts it
  while it is blocked in an I/O operation upon a channel.Before this
  exception is thrown the channel will have been closed and the interrupt
  status of the previously-blocked thread will have been set.
 @since 1.4
 */
@interface JavaNioChannelsClosedByInterruptException : JavaNioChannelsAsynchronousCloseException

#pragma mark Public

/*!
 @brief Constructs an instance of this class.
 */
- (instancetype __nonnull)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioChannelsClosedByInterruptException)

FOUNDATION_EXPORT void JavaNioChannelsClosedByInterruptException_init(JavaNioChannelsClosedByInterruptException *self);

FOUNDATION_EXPORT JavaNioChannelsClosedByInterruptException *new_JavaNioChannelsClosedByInterruptException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaNioChannelsClosedByInterruptException *create_JavaNioChannelsClosedByInterruptException_init(void);

J2OBJC_TYPE_LITERAL_HEADER(JavaNioChannelsClosedByInterruptException)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_JavaNioChannelsClosedByInterruptException")
