//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/android/build_result/java/com/google/common/collect/AbstractSortedMultiset.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedMultiset")
#ifdef RESTRICT_ComGoogleCommonCollectAbstractSortedMultiset
#define INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedMultiset 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedMultiset 1
#endif
#undef RESTRICT_ComGoogleCommonCollectAbstractSortedMultiset

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectAbstractSortedMultiset_) && (INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedMultiset || defined(INCLUDE_ComGoogleCommonCollectAbstractSortedMultiset))
#define ComGoogleCommonCollectAbstractSortedMultiset_

#define RESTRICT_ComGoogleCommonCollectAbstractMultiset 1
#define INCLUDE_ComGoogleCommonCollectAbstractMultiset 1
#include "com/google/common/collect/AbstractMultiset.h"

#define RESTRICT_ComGoogleCommonCollectSortedMultiset 1
#define INCLUDE_ComGoogleCommonCollectSortedMultiset 1
#include "com/google/common/collect/SortedMultiset.h"

@class ComGoogleCommonCollectBoundType;
@protocol ComGoogleCommonCollectMultiset_Entry;
@protocol JavaUtilComparator;
@protocol JavaUtilIterator;
@protocol JavaUtilNavigableSet;

/*!
 @brief This class provides a skeletal implementation of the <code>SortedMultiset</code> interface.
 <p>The <code>count</code> and <code>size</code> implementations all iterate across the set returned by 
 <code>Multiset.entrySet()</code>, as do many methods acting on the set returned by <code>elementSet()</code>
 . Override those methods for better performance.
 @author Louis Wasserman
 */
@interface ComGoogleCommonCollectAbstractSortedMultiset : ComGoogleCommonCollectAbstractMultiset < ComGoogleCommonCollectSortedMultiset > {
 @public
  id<JavaUtilComparator> comparator_;
}

#pragma mark Public

- (id<JavaUtilComparator>)comparator;

- (id<ComGoogleCommonCollectSortedMultiset>)descendingMultiset;

- (id<JavaUtilNavigableSet>)elementSet;

- (id<ComGoogleCommonCollectMultiset_Entry>)firstEntry;

- (id<ComGoogleCommonCollectMultiset_Entry>)lastEntry;

- (id<ComGoogleCommonCollectMultiset_Entry>)pollFirstEntry;

- (id<ComGoogleCommonCollectMultiset_Entry>)pollLastEntry;

- (id<ComGoogleCommonCollectSortedMultiset>)subMultisetWithId:(id __nullable)fromElement
                          withComGoogleCommonCollectBoundType:(ComGoogleCommonCollectBoundType * __nonnull)fromBoundType
                                                       withId:(id __nullable)toElement
                          withComGoogleCommonCollectBoundType:(ComGoogleCommonCollectBoundType * __nonnull)toBoundType;

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivate;

- (instancetype __nonnull)initPackagePrivateWithJavaUtilComparator:(id<JavaUtilComparator> __nonnull)comparator;

- (id<ComGoogleCommonCollectSortedMultiset>)createDescendingMultiset;

- (id<JavaUtilNavigableSet>)createElementSet;

- (id<JavaUtilIterator>)descendingEntryIterator;

- (id<JavaUtilIterator>)descendingIterator;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectAbstractSortedMultiset)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectAbstractSortedMultiset, comparator_, id<JavaUtilComparator>)

FOUNDATION_EXPORT void ComGoogleCommonCollectAbstractSortedMultiset_initPackagePrivate(ComGoogleCommonCollectAbstractSortedMultiset *self);

FOUNDATION_EXPORT void ComGoogleCommonCollectAbstractSortedMultiset_initPackagePrivateWithJavaUtilComparator_(ComGoogleCommonCollectAbstractSortedMultiset *self, id<JavaUtilComparator> comparator);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectAbstractSortedMultiset)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedMultiset")
