//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/android/build_result/java/com/google/common/collect/ListMultimap.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectListMultimap")
#ifdef RESTRICT_ComGoogleCommonCollectListMultimap
#define INCLUDE_ALL_ComGoogleCommonCollectListMultimap 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectListMultimap 1
#endif
#undef RESTRICT_ComGoogleCommonCollectListMultimap

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectListMultimap_) && (INCLUDE_ALL_ComGoogleCommonCollectListMultimap || defined(INCLUDE_ComGoogleCommonCollectListMultimap))
#define ComGoogleCommonCollectListMultimap_

#define RESTRICT_ComGoogleCommonCollectMultimap 1
#define INCLUDE_ComGoogleCommonCollectMultimap 1
#include "com/google/common/collect/Multimap.h"

@protocol JavaLangIterable;
@protocol JavaUtilList;
@protocol JavaUtilMap;

/*!
 @brief A <code>Multimap</code> that can hold duplicate key-value pairs and that maintains the insertion
  ordering of values for a given key.See the <code>Multimap</code> documentation for information common
  to all multimaps.
 <p>The <code>get</code>, <code>removeAll</code>, and <code>replaceValues</code> methods each return a <code>List</code>
  of values. Though the method signature doesn't say so explicitly, the map returned by 
 <code>asMap</code> has <code>List</code> values. 
 <p>See the Guava User Guide article on <a href="https://github.com/google/guava/wiki/NewCollectionTypesExplained#multimap">
  <code>Multimap</code>
 </a>.
 @author Jared Levy
 @since 2.0
 */
@protocol ComGoogleCommonCollectListMultimap < ComGoogleCommonCollectMultimap, JavaObject >

/*!
 @brief <p>Because the values for a given key may have duplicates and follow the insertion ordering,
  this method returns a <code>List</code>, instead of the <code>java.util.Collection</code> specified in
  the <code>Multimap</code> interface.
 */
- (id<JavaUtilList>)getWithId:(id __nullable)key;

/*!
 @brief <p>Because the values for a given key may have duplicates and follow the insertion ordering,
  this method returns a <code>List</code>, instead of the <code>java.util.Collection</code> specified in
  the <code>Multimap</code> interface.
 */
- (id<JavaUtilList>)removeAllWithId:(id __nullable)key;

/*!
 @brief <p>Because the values for a given key may have duplicates and follow the insertion ordering,
  this method returns a <code>List</code>, instead of the <code>java.util.Collection</code> specified in
  the <code>Multimap</code> interface.
 */
- (id<JavaUtilList>)replaceValuesWithId:(id __nonnull)key
                   withJavaLangIterable:(id<JavaLangIterable> __nonnull)values;

/*!
 @brief <p><b>Note:</b> The returned map's values are guaranteed to be of type <code>List</code>.
 To obtain
  this map with the more specific generic type <code>Map<K, List<V>></code>, call <code>Multimaps.asMap(ListMultimap)</code>
  instead.
 */
- (id<JavaUtilMap>)asMap;

/*!
 @brief Compares the specified object to this multimap for equality.
 <p>Two <code>ListMultimap</code> instances are equal if, for each key, they contain the same values
  in the same order. If the value orderings disagree, the multimaps will not be considered equal. 
 <p>An empty <code>ListMultimap</code> is equal to any other empty <code>Multimap</code>, including an
  empty <code>SetMultimap</code>.
 */
- (jboolean)isEqual:(id __nullable)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectListMultimap)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectListMultimap)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectListMultimap")
