//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/guava/build_result/java/com/google/common/io/RecursiveDeleteOption.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonIoRecursiveDeleteOption")
#ifdef RESTRICT_ComGoogleCommonIoRecursiveDeleteOption
#define INCLUDE_ALL_ComGoogleCommonIoRecursiveDeleteOption 0
#else
#define INCLUDE_ALL_ComGoogleCommonIoRecursiveDeleteOption 1
#endif
#undef RESTRICT_ComGoogleCommonIoRecursiveDeleteOption

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonIoRecursiveDeleteOption")
